### ISSUE TITLE
ToDo reference sample crashes when clicking the SettingsView button.  Possibly related to localizer

### ISSUE THREAD

**Issue by wartron** [unoplatform/Uno.Samples#676]
When clicking the top button the mock current user "Foo Bar" which opens the SettingsView

```
System.Runtime.InteropServices.COMException
  HResult=0x8001010E
  Message=
  Source=WinRT.Runtime
  StackTrace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Microsoft.UI.Xaml.IWindowMethods.get_Content(IObjectReference _obj)
   at Microsoft.UI.Xaml.Window.get_Content()
   at ToDo.AppTheme.get_IsDark() in C:\Users\wartron\code\uno\Uno.Samples\reference\ToDo\src\ToDo.UI\AppTheme.cs:line 14
   at ToDo.Presentation.SettingsViewModel.<>c__DisplayClass15_0.<.ctor>b__0() in C:\Users\wartron\code\uno\Uno.Samples\reference\ToDo\src\ToDo\Presentation\SettingsViewModel.cs:line 42
   at Uno.Extensions.Reactive.State`1.<>c__5`1.<Value>b__5_0(TOwner o, Func`1 v)
   at Uno.Extensions.Reactive.Utils.AttachedProperty.GetOrCreate[TOwner,TKey,TValue](TOwner owner, TKey key, Factory`3 factory)
   at Uno.Extensions.Reactive.State`1.Value[TOwner](TOwner owner, Func`1 valueProvider)
   at Uno.Extensions.Reactive.State.Value[TOwner,TValue](TOwner owner, Func`1 valueProvider)
   at ToDo.Presentation.SettingsViewModel..ctor(NavigationRequest request, INavigator navigator, IAuthenticationService authService, IUserProfilePictureService userSvc, IOptions`1 localizationConfiguration, ILocalizationService localizationSettings, IStringLocalizer localizer, IAppTheme appTheme, IWritableOptions`1 appSettings) in C:\Users\wartron\code\uno\Uno.Samples\reference\ToDo\src\ToDo\Presentation\SettingsViewModel.cs:line 42
   at ToDo.Presentation.BindableSettingsViewModel..ctor(NavigationRequest request, INavigator navigator, IAuthenticationService authService, IUserProfilePictureService userSvc, IOptions`1 localizationConfiguration, ILocalizationService localizationSettings, IStringLocalizer localizer, IAppTheme appTheme, IWritableOptions`1 appSettings) in C:\Users\wartron\code\uno\Uno.Samples\reference\ToDo\src\ToDo\Uno.Extensions.Reactive.Generator\Uno.Extensions.Reactive.Generator.FeedsGenerator\ToDo.Presentation.SettingsViewModel.Bindable.g.cs:line 26
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithManyArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Uno.Extensions.Navigation.Navigators.ControlNavigator.<>c__DisplayClass8_0.<<CreateViewModel>b__0>d.MoveNext()
```

So i figured i'd just default this line in SettingViewModel.cs to just 0
```
SelectedAppTheme = State.Value(this, () => AppThemes[appTheme.IsDark ? 1 : 0]);

to

SelectedAppTheme = State.Value(this, () => AppThemes[0]);
```

and then it breaks at the line 
```

        Cultures = localizationConfiguration.Value!.Cultures!.Select(c => new DisplayCulture(localizer[$"SettingsFlyout_LanguageLabel_{c}"], c)).ToArray();
```

with this error

```
System.ArgumentNullException
  HResult=0x80004003
  Message=Value cannot be null. (Parameter 'source')
  Source=System.Linq
  StackTrace:
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at ToDo.Presentation.SettingsViewModel..ctor(NavigationRequest request, INavigator navigator, IAuthenticationService authService, IUserProfilePictureService userSvc, IOptions`1 localizationConfiguration, ILocalizationService localizationSettings, IStringLocalizer localizer, IAppTheme appTheme, IWritableOptions`1 appSettings) in C:\Users\wartron\code\uno\Uno.Samples\reference\ToDo\src\ToDo\Presentation\SettingsViewModel.cs:line 46
   at ToDo.Presentation.BindableSettingsViewModel..ctor(NavigationRequest request, INavigator navigator, IAuthenticationService authService, IUserProfilePictureService userSvc, IOptions`1 localizationConfiguration, ILocalizationService localizationSettings, IStringLocalizer localizer, IAppTheme appTheme, IWritableOptions`1 appSettings) in C:\Users\wartron\code\uno\Uno.Samples\reference\ToDo\src\ToDo\Uno.Extensions.Reactive.Generator\Uno.Extensions.Reactive.Generator.FeedsGenerator\ToDo.Presentation.SettingsViewModel.Bindable.g.cs:line 26
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithManyArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Uno.Extensions.Navigation.Navigators.ControlNavigator.<>c__DisplayClass8_0.<<CreateViewModel>b__0>d.MoveNext()

```

Uno and Samples where downleded May 3rd, 2024

**Comment by wartron** [comment]
Noticed this in the console also

```
Uno.Extensions.Storage.FileStorage: Warning: ReadPackageFileAsync - File 'appsettings.keyvaluestorageconfiguration.json' does not exist in package
Uno.Extensions.Storage.FileStorage: Warning: ReadPackageFileAsync - File 'appsettings.platform.development.json' does not exist in package
Uno.Extensions.Storage.FileStorage: Warning: ReadPackageFileAsync - File 'appsettings.auth.json' does not exist in package
Uno.Extensions.Storage.FileStorage: Warning: ReadPackageFileAsync - File 'appsettings.mock.json' does not exist in package
Uno.Extensions.Storage.FileStorage: Warning: ReadPackageFileAsync - File 'appsettings.todoapp.json' does not exist in package
Uno.Extensions.Storage.FileStorage: Warning: ReadPackageFileAsync - File 'appsettings.localizationconfiguration.json' does not exist in package
Uno.Extensions.Storage.FileStorage: Warning: ReadPackageFileAsync - File 'appsettings.localizationsettings.json' does not exist in package
```

**Comment by agneszitte** [comment]
Thank you a lot for the feedback @wartron, we will investigate

**Comment by agneszitte** [comment]
@rajamatt this change should fix that normally, if you can confirm while doing the migration for the sample please

https://github.com/unoplatform/Uno.Samples/pull/647/commits/9aced5a44d54ab0fc34a3cba825f6a140fcaf677#diff-9e05464af3677fc9cea58942074e92b11426f00ab6c27e465804e9c69c2e4882R49

**Comment by agneszitte** [comment]
Related PR for coming changes for single project migration and fix for this issue: https://github.com/unoplatform/Uno.Samples/pull/745
