### ISSUE TITLE
[SQLite][Wasm]  Not building the application 

### ISSUE THREAD

**Issue by Darsh0307** [unoplatform/Uno.Samples#706]
Its taking forever when building with wasm. the same one is working for android and windows
Its loading the screen but not able to run the application

**WASM**
```

System.IO.FileNotFoundException: Cannot start debug proxy because its path cannot be determined.
   at Uno.Wasm.Bootstrap.Cli.DebugProxyLauncher.LocateDebugProxyExecutable(IWebHostEnvironment environment, IConfiguration configuration) in /_/src/Uno.Wasm.Bootstrap.Cli/DebuggingProxy/DebugProxyLauncher.cs:line 160
   at Uno.Wasm.Bootstrap.Cli.DebugProxyLauncher.LaunchAndGetUrl(IServiceProvider serviceProvider, IConfiguration configuration, String devToolsHost, Uri browserUrl) in /_/src/Uno.Wasm.Bootstrap.Cli/DebuggingProxy/DebugProxyLauncher.cs:line 141
   at Uno.Wasm.Bootstrap.Cli.DebugProxyLauncher.EnsureLaunchedAndGetUrl(IServiceProvider serviceProvider, IConfiguration configuration, String devToolsHost, Uri browserUrl) in /_/src/Uno.Wasm.Bootstrap.Cli/DebuggingProxy/DebugProxyLauncher.cs:line 75
   at Uno.Wasm.Bootstrap.Cli.DebuggingProxy.DebuggerHostExtensions.<>c__DisplayClass0_0.<<UseWebAssemblyDebugging>b__1>d.MoveNext() in /_/src/Uno.Wasm.Bootstrap.Cli/DebuggingProxy/DebugHostExtensions.cs:line 66
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.InvokeCore(HttpContext context, PathString matchedPath, PathString remainingPath)
   at Uno.Wasm.Bootstrap.Cli.Server.Startup.<>c__DisplayClass2_0.<<Configure>b__0>d.MoveNext() in /_/src/Uno.Wasm.Bootstrap.Cli/Server/Startup.cs:line 77
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
The program '' has exited with code 4294967295 (0xffffffff).
The thread '[Thread Destroyed]' (15260) has exited with code 0 (0x0).
The thread '[Thread Destroyed]' (4492) has exited with code 0 (0x0).
The thread '[Thread Destroyed]' (17808) has exited with code 0 (0x0).
```
[SQLiteSample.zip](https://github.com/unoplatform/Uno.Samples/files/15414221/SQLiteSample.zip)

**Comment by jeromelaban** [comment]
This is likely going to be fixed by updating to latest uno, or updating to single project.
