### ISSUE TITLE
SqLiteSample does not work when adding EF Core

### ISSUE THREAD

**Issue by groogiam** [unoplatform/Uno.Samples#81]
The sample breaks when adding

<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite.Core" Version="5.0.12" />

See below stack trace:

```
Failed to raise 'PointerReleasedEvent': System.TypeInitializationException: TypeInitialization_Type, SQLite.SQLiteConnection
dotnet.js:2373        ---> System.TypeLoadException: VTable setup of type SQLitePCL.SQLite3Provider_sqlite3 failed
dotnet.js:2373          at SQLite.SQLiteConnection..cctor()
dotnet.js:2373          Exception_EndOfInnerExceptionStack
dotnet.js:2373          at SQLiteSample.MainPage.TryCreateDatabase() in C:\Users\Greg\Desktop\Uno.Samples\UI\SQLiteSample\SQLiteSample\SQLiteSample\SQLiteSample.Shared\MainPage.xaml.cs:line 61
dotnet.js:2373          at SQLiteSample.MainPage.<InitializeDatabase>d__1.MoveNext() in C:\Users\Greg\Desktop\Uno.Samples\UI\SQLiteSample\SQLiteSample\SQLiteSample\SQLiteSample.Shared\MainPage.xaml.cs:line 38
dotnet.js:2373          at SQLiteSample.MainPage.TryCreateDatabase() in C:\Users\Greg\Desktop\Uno.Samples\UI\SQLiteSample\SQLiteSample\SQLiteSample\SQLiteSample.Shared\MainPage.xaml.cs:line 61
dotnet.js:2373          at SQLiteSample.MainPage.OnClickMe() in C:\Users\Greg\Desktop\Uno.Samples\UI\SQLiteSample\SQLiteSample\SQLiteSample\SQLiteSample.Shared\MainPage.xaml.cs:line 46
dotnet.js:2373          at SQLiteSample.MainPage.<>c__DisplayClass6_2.<InitializeComponent>b__9(Object _sender, RoutedEventArgs _e) in C:\Users\Greg\Desktop\Uno.Samples\UI\SQLiteSample\SQLiteSample\SQLiteSample\SQLiteSample.Wasm\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGenerator\MainPage_e02ddde003dafe62614502781685a19d.cs:line 109
```

I have been working on this for several hours and cannot get Sqlite to work with EFCore.

**Comment by jeromelaban** [comment]
See the documentation and samples for SQLite support here: https://github.com/unoplatform/Uno.SQLitePCLRaw.Wasm

**Comment by groogiam** [comment]
These do not seem to run in their current state against the release version of .NET 6. I'll try and upgrade the package references to see if I can get them to work but just wanted you to make you all aware of this. 

![image](https://user-images.githubusercontent.com/1992395/143281289-b05318b1-c646-4fde-b911-fa00a52cb9bd.png)

**Comment by groogiam** [comment]
I was able to get this working by updating the package references. Thanks for pointing me in the right direction.
